name: d_store
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

#---------------- PACKAGES ----------------#
dependencies:
  flutter:
    sdk: flutter

# UTILITY PACKAGES
  logger: ^2.0.1
  url_launcher: ^6.1.12
  intl: ^0.18.1
  http: ^1.1.0
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  

# ICONS 
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

# STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1

# PRODUCE SPECIFIC
  readmore: ^3.0.0
  carousel_slider: ^5.1.1

# FIREBASE
  firebase_core: ^4.0.0


#---------------- PACKAGES END ----------------#

  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1
  lottie: ^3.3.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#---------------- LOCAL ASSETS ----------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/images/NikeAF1/
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/fonts/

#---------------- LOCAL FONTS ----------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
