// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7gPI3DKDIm1t1TNAoxmUdV6lDt6reEA',
    appId: '1:661377076963:web:5df0cfe071eb26ce9cbfd6',
    messagingSenderId: '661377076963',
    projectId: 'ecommerceapp-db59a',
    authDomain: 'ecommerceapp-db59a.firebaseapp.com',
    storageBucket: 'ecommerceapp-db59a.firebasestorage.app',
    measurementId: 'G-FXSEQF4HBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZTaI-1Gph4C4dEwf6-zt8De1XcLFoCI',
    appId: '1:661377076963:android:aa51c3ffc75864499cbfd6',
    messagingSenderId: '661377076963',
    projectId: 'ecommerceapp-db59a',
    storageBucket: 'ecommerceapp-db59a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6c_gHPfACgpGzFc5vtyF4iX7qIxxHav8',
    appId: '1:661377076963:ios:717428fcea1d86f29cbfd6',
    messagingSenderId: '661377076963',
    projectId: 'ecommerceapp-db59a',
    storageBucket: 'ecommerceapp-db59a.firebasestorage.app',
    androidClientId: '661377076963-0fbe14qldsuaqra4sr1qgmn89899mvll.apps.googleusercontent.com',
    iosClientId: '661377076963-pnhv2bp7ls8ge5isepj15kh082ejdkf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6c_gHPfACgpGzFc5vtyF4iX7qIxxHav8',
    appId: '1:661377076963:ios:717428fcea1d86f29cbfd6',
    messagingSenderId: '661377076963',
    projectId: 'ecommerceapp-db59a',
    storageBucket: 'ecommerceapp-db59a.firebasestorage.app',
    androidClientId: '661377076963-0fbe14qldsuaqra4sr1qgmn89899mvll.apps.googleusercontent.com',
    iosClientId: '661377076963-pnhv2bp7ls8ge5isepj15kh082ejdkf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP7gPI3DKDIm1t1TNAoxmUdV6lDt6reEA',
    appId: '1:661377076963:web:9391b37341498b909cbfd6',
    messagingSenderId: '661377076963',
    projectId: 'ecommerceapp-db59a',
    authDomain: 'ecommerceapp-db59a.firebaseapp.com',
    storageBucket: 'ecommerceapp-db59a.firebasestorage.app',
    measurementId: 'G-0L29VS0WVW',
  );

}